storage:
  type: s3
  bucket: local-data

datasets:
  era5-daily:
    name: reanalysis-era5-single-levels
    url: https://cds.climate.copernicus.eu/api
    key: ${CDSAPI_KEY}
    granularity: daily
    years: [2024, 2025]
    min_date: 2024-01-01
    fail_on_error: true
    request:
      product_type: ["reanalysis"]
      variable:
        - "2m_temperature"
        - "total_precipitation"
        - "instantaneous_10m_wind_gust"
        - "clear_sky_direct_solar_radiation_at_surface"
        - "cloud_base_height"
        - "large_scale_rain_rate"
        - "large_scale_precipitation"
        - "large_scale_snowfall"
        - "snowfall"
      time: ["00:00", "06:00", "12:00", "18:00"]
      data_format: grib
      download_format: unarchived
      area: [45.96, 11.11, 45.84, 11.36]
